#Для реализации безопасного CI/CD пайплайна выбран проект DefectDojo — open-source платформа для управления уязвимостями на Python/Django. Пайплайн построен на GitHub Actions с интеграцией инструментов безопасности и автоматизированным деплоем на VPS.
#
#————————
#
#Этап 1: CI/CD Pipeline
#Инструменты: GitHub Actions, Docker, Nginx.  
#Конфигурация:
name: Secure Pipeline
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Build Docker image
        run: docker build -t defectdojo:latest .

  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Deploy to VPS
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.VPS_IP }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            docker pull defectdojo:latest
            docker-compose up -d


