name: CI/CD Pipeline
on: push

jobs:
  build:
       runs-on: ubuntu-latest
       steps:
         - name: Checkout code
           uses: actions/checkout@v4

         - name: Build the project
           run: |
             echo "Building the project..."
             docker build -t defectdojo .

  test:
       runs-on: ubuntu-latest
       needs: build
       steps:
         - name: Checkout code
           uses: actions/checkout@v4

         - name: Run tests
           run: |
             echo "Running tests..."
             docker run defectdojo pytest

  deploy:
      runs-on: ubuntu-latest
      needs: test
      steps:
         - name: Deploy to production
           run: |
             echo "Deploying to production..."
             ssh user@vps "docker run -d --rm --name defectdojo -p 8000:8000 defectdojo"

