name: sast
on: push

jobs:
 test:
  runs-on: ubuntu-latest
  steps:
  - name: chec
    uses: actions/checkout@v4

  - name: Run Semgrep
    uses: returntocorp/semgrep-action@v1
    with:
      config: p/python

  - name: Dependency check
    uses: dependabot/fetch-metadata@v2
